[package]
name = "blkview"
version = "0.1.0"
authors = ["Souvik Banerjee <souvik1997@gmail.com>"]

[dependencies]
clap = "~2.31"
num = "~0.1.42"
num-derive = "~0.2.0"
num-traits = "~0.2.2"
bitflags = "~1.0.1"
gif = "~0.9.2"
rayon = "~1.0.1"
image = "~0.18.0"
palette = "~0.3.0"